In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Bengaluru Ola.csv')

In [4]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Rating
0,28/01/2024,6:00:00,CNR1721175,Success,329258,Auto,Area-3,Area-2,5.42,18.46,...,NaN,0,NaN,0,NaN,868.06,Wallet,28.5,4.4,4.4
1,26/01/2024,3:00:00,CNR2871422,Cancelled by Driver,201414,Mini,Area-7,Area-6,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
2,15/01/2024,16:00:00,CNR6875935,Cancelled by Driver,301629,Bike,Area-40,Area-24,NaN,NaN,...,NaN,1,Personal & Car related issues,0,NaN,NaN,NaN,NaN,NaN,NaN
3,02/01/2024,22:00:00,CNR6798834,Cancelled by Driver,319684,Prime Sedan,Area-11,Area-24,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
4,30/01/2024,22:00:00,CNR9661713,Incomplete,330283,Bike,Area-41,Area-45,NaN,NaN,...,NaN,0,NaN,1,Other Issue,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(49999, 21)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               49999 non-null  object
 1   Time                               49999 non-null  object
 2   Booking ID                         49999 non-null  object
 3   Booking Status                     49999 non-null  object
 4   Customer ID                        49999 non-null  int64
 5   Vehicle Type                       49999 non-null  object
 6   Pickup Location                    49999 non-null  object
 7   Drop Location                      49999 non-null  object
 8   Avg VTAT                           33484 non-null  float64
 9   Avg CTAT                           33484 non-null  float64
 10  Cancelled  by Customer             49999 non-null  int64
 11  Reason for Cancelling by Customer  3799 non-null   object
 12  Cancelled Rides by Driver          49999 non-null  int64
 13  Reason for Cancelling by Driver    9610 non-null   object
 14  Incomplete Rides                   49999 non-null  int64
 15  Incomplete Rides Reason            3106 non-null   object
 16  Booking Value                      33484 non-null  float64
 17  Payment Method                     33484 non-null  object
 18  Ride Distance                      33484 non-null  float64
 19  Driver Ratings                     33484 non-null  float64
 20  Customer Rating                    33484 non-null  float64
dtypes: float64(6), int64(4), object(11)
memory usage: 8.0+ MB

In [7]:
df['Reason for Cancelling by Customer'].value_counts()

Reason for Cancelling by Customer
Driver is not moving towards pickup location    793
AC is not working                               792
Change of plans                                 756
Driver asked to cancel                          738
Wrong Address                                   720
Name: count, dtype: int64

In [9]:
df.groupby('Booking Status')[['Booking Value']].count()

                       Booking Value
Booking Status
Cancelled by Customer              0
Cancelled by Driver                0
Incomplete                         0
Success                        33484

In [47]:
RAW_PATH = "Bengaluru_Ola.csv"
OUT_PATH = "Bengaluru_Ola_cleaned.csv"

In [11]:
df['Booking Status'].value_counts

<bound method IndexOpsMixin.value_counts of 0                    Success
1        Cancelled by Driver
2        Cancelled by Driver
3        Cancelled by Driver
4                 Incomplete
                ...
49994                Success
49995                Success
49996    Cancelled by Driver
49997                Success
49998                Success
Name: Booking Status, Length: 49999, dtype: object>

In [13]:
df.columns = [c.strip().replace("  ", " ") for c in df.columns]

In [14]:
df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled by Customer',
       'Reason for Cancelling by Customer', 'Cancelled Rides by Driver',
       'Reason for Cancelling by Driver', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Payment Method',
       'Ride Distance', 'Driver Ratings', 'Customer Rating'],
      dtype='object')

In [17]:
df['ride_datetime'] =  pd.to_datetime(df['Date'] + " " + df['Time'], format = "%d/%m/%Y %H:%M:%S")

In [19]:
df['ride_datetime'].head()

0   2024-01-28 06:00:00
1   2024-01-26 03:00:00
2   2024-01-15 16:00:00
3   2024-01-02 22:00:00
4   2024-01-30 22:00:00
Name: ride_datetime, dtype: datetime64[ns]

In [20]:
df['day_of_week'] = df['ride_datetime'].dt.day_name()

In [22]:
df['hour'] = df['ride_datetime'].dt.hour

In [23]:
df['hour']

0         6
1         3
2        16
3        22
4        22
         ..
49994     0
49995     2
49996    23
49997    22
49998    14
Name: hour, Length: 49999, dtype: int32

In [28]:
df['Booking ID'].duplicated().sum()

np.int64(133)

In [29]:
df[df['Booking ID'].duplicated(keep=False)].sort_values('Booking ID')

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Incomplete Rides,Incomplete Rides Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Rating,ride_datetime,day_of_week,hour
8307,29/01/2024,14:00:00,CNR0302648,Incomplete,394353,Mini,Area-24,Area-4,NaN,NaN,...,1,Customer Demand,NaN,NaN,NaN,NaN,NaN,2024-01-29 14:00:00,Monday,14
6628,13/01/2024,22:00:00,CNR0302648,Success,331256,Bike,Area-43,Area-24,8.65,22.39,...,0,NaN,1700.77,Card,14.76,4.3,3.5,2024-01-13 22:00:00,Saturday,22
48267,29/01/2024,7:00:00,CNR0305285,Success,386209,Auto,Area-30,Area-23,8.55,20.53,...,0,NaN,377.07,UPI,41.60,4.3,3.0,2024-01-29 07:00:00,Monday,7
26871,10/01/2024,3:00:00,CNR0305285,Success,876053,Mini,Area-4,Area-29,10.57,26.70,...,0,NaN,779.27,UPI,9.51,4.0,4.2,2024-01-10 03:00:00,Wednesday,3
48876,15/01/2024,4:00:00,CNR0347004,Cancelled by Customer,541082,Prime SUV,Area-20,Area-33,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-15 04:00:00,Monday,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15433,17/01/2024,9:00:00,CNR9931058,Cancelled by Driver,598216,Prime SUV,Area-15,Area-36,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-17 09:00:00,Wednesday,9
4993,14/01/2024,20:00:00,CNR9970880,Cancelled by Driver,726241,Mini,Area-45,Area-33,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-14 20:00:00,Sunday,20
27552,19/01/2024,14:00:00,CNR9970880,Success,413461,Prime Sedan,Area-44,Area-9,10.46,3.16,...,0,NaN,1758.68,Card,33.88,3.5,3.3,2024-01-19 14:00:00,Friday,14
44227,16/01/2024,19:00:00,CNR9987795,Success,200180,Prime Plus,Area-6,Area-2,13.86,1.67,...,0,NaN,1749.86,Cash,26.19,4.0,3.4,2024-01-16 19:00:00,Tuesday,19
34274,12/01/2024,12:00:00,CNR9987795,Success,458596,Auto,Area-9,Area-23,7.13,3.17,...,0,NaN,777.04,Card,8.56,4.4,3.7,2024-01-12 12:00:00,Friday,12

In [30]:
df['ride_id'] = 'RIDE' + df.index.astype(str).str.zfill(6)

In [31]:
df['ride_id']

0        RIDE000000
1        RIDE000001
2        RIDE000002
3        RIDE000003
4        RIDE000004
            ...
49994    RIDE049994
49995    RIDE049995
49996    RIDE049996
49997    RIDE049997
49998    RIDE049998
Name: ride_id, Length: 49999, dtype: object

In [33]:
df['is_completed'] = df['Booking Status'] == 'Success'

In [38]:
reason_cols = ['Reason for Cancelling by Customer', 'Reason for Cancelling by Driver', 'Incomplete Rides Reason']
for col in reason_cols:
    df[col] = df[col].fillna('Not Applicable')

In [42]:
def area_to_zone(area_str):
    area_num = int(area_str.split("-")[1])
    zone_num = ((area_num - 1) * 8 // 50) + 1
    return f"Zone-{zone_num}"

In [43]:
df["pickup_zone"] = df["Pickup Location"].apply(area_to_zone)
df["drop_zone"] = df["Drop Location"].apply(area_to_zone)

In [45]:
df.to_csv(OUT_PATH, index=False)

In [51]:
naive_avg = pd.read_csv('Bengaluru Ola.csv')["Booking Value"].fillna(0).mean()
correct_avg = df.loc[df["is_completed"], "Booking Value"].mean()
error_pct = abs(naive_avg - correct_avg) / correct_avg * 100
 
print("Rows before:", len(pd.read_csv('Bengaluru Ola.csv')))
print("Rows after:", len(df))
print("Duplicate Booking IDs fixed:", pd.read_csv('Bengaluru Ola.csv')["Booking ID"].duplicated().sum())
print("Zones created:", df["pickup_zone"].nunique())
print(f"Accuracy error avoided by not zero-filling: {error_pct:.1f}%")

Rows before: 49999
Rows after: 49999
Duplicate Booking IDs fixed: 133
Zones created: 8
Accuracy error avoided by not zero-filling: 33.0%